//
// Created by dxt on 18-11-26.
//

#ifndef SOLARENERGYRAYTRACING_RAYTRACINGPIPELINE_H
#define SOLARENERGYRAYTRACING_RAYTRACINGPIPELINE_H

void RayTracingPipeline(int argc, char *argv[]);

#endif //SOLARENERGYRAYTRACING_RAYTRACINGPIPELINE_H
